### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Muhiyaddeen** [ShadowMonster99/millennium-steam-binaries#2]
![Screenshot 2024-03-09 105948](https://github.com/ShadowMonster99/millennium-steam-binaries/assets/135968862/a7e1bc26-a286-42a0-b709-2baf8351e4a6)
i just installed it yesterday and this morning after update its gone and when i installed it again its does not work properly it only applies black skin for store and community page not library page not any custom looks for buttons as well please help me with this i loved the new look for the steam

**Comment by Muhiyaddeen** [comment]
it was working perfectly

**Comment by ShadowMonster99** [comment]
use beta mode on steam for now. large changes have been made to steam that currently trumps their support. hopefully it will be resolved in the future.
